### springcloud-provider-dev8001.yml
server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservice1-8001
    prefer-ip-address: true

info:
  app:
    name:
      microservice1-8001
    company:
      name: company1
    build:
      artifactId: $project.artifactId$
      version: $project.version$
